from simulator import Simulator
s = Simulator()
ass = s.reset()
s.map.render()
ass = s.step(ass[2][3][2])
s.map.render()
ass = s.step(ass[2][3][2])
s.map.render()
ass = s.step(ass[2][3][2])
s.map.render()
